[ids]
*

[main]
# esc when tapped, ctrl when held
capslock = overload(control, esc)

# no media keys on thinkpad t14s
f21 = previoussong
f22 = playpause
f23 = nextsong

# swap grave/tilde with <>
grave = 102nd
102nd = grave
