[packages.arch]
pacman = [
  "base-devel",
  "bat",
  "curl",
  "direnv",
  "eza",
  "fastfetch",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "hyprland",
  "hyprpolkitagent",
  "inter-font",
  "jq",
  "lazygit",
  "less",
  "man-db",
  "man-pages",
  "musescore",
  "neovim",
  "obsidian",
  "otf-font-awesome",
  "rbw",
  "ripgrep",
  "showmethekey",
  "starship",
  "tldr",
  "tmux",
  "tree-sitter-cli",
  "ttf-jetbrains-mono-nerd",
  "typst",
  "unzip",
  "uv",
  "wev",
  "wl-clipboard",
  "xdg-user-dirs",
  "yazi",
  "yt-dlp",
  "zoxide",
  "zsh",
]
aur = [
  "deezer-enhanced-bin",
  "pi",
  "kanata",
  "noctalia-git",
  "zen-browser-bin",
]
npm = ["@earendil-works/pi-coding-agent"]

[packages.darwin]
taps = ["derailed/k9s", "nikitabobko/tap"]
brews = [
  "bat",
  "coreutils",
  "direnv",
  "evtest",
  "eza",
  "fastfetch",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "jq",
  "kanata",
  "kubectx",
  "lazygit",
  "neovim",
  "rbw",
  "ripgrep",
  "starship",
  "tmux",
  "tree-sitter-cli",
  "typst",
  "uv",
  "yazi",
  "zoxide",

  "derailed/k9s/k9s",
]
casks = [
  "android-platform-tools",
  "docker-desktop",
  "font-fontawesome",
  "font-jetbrains-mono-nerd-font",
  "ghostty",
  "karabiner-elements",
  "deezer",

  "nikitabobko/tap/aerospace",
]
npm = ["@earendil-works/pi-coding-agent"]
