[packages.arch]
pacman = [
  "base-devel",
  "bat",
  "curl",
  "direnv",
  "eza",
  "fastfetch",
  "fd",
  "fzf",
  "ghostty",
  "git",
  "git-delta",
  "jq",
  "keyd",
  "lazygit",
  "less",
  "man-db",
  "man-pages",
  "neovim",
  "npm",
  "rbw",
  "ripgrep",
  "starship",
  "tldr",
  "tmux",
  "tree-sitter-cli",
  "ttf-jetbrains-mono-nerd",
  "uv",
  "wl-clipboard",
  "yazi",
  "yt-dlp",
  "zoxide",
  "zsh",
]
aur = ["zen-browser-bin", "spotify"]
npm = ["@earendil-works/pi-coding-agent"]

[packages.darwin]
taps = ["derailed/k9s", "ozeias/postgresql", "nikitabobko/tap"]
brews = [
  "bat",
  "coreutils",
  "direnv",
  "eza",
  "fastfetch",
  "fd",
  "fzf",
  "git",
  "git-delta",
  "jq",
  "kubectx",
  "lazygit",
  "neovim",
  "rbw",
  "ripgrep",
  "starship",
  "tree-sitter-cli",
  "uv",
  "yazi",
  "yt-dlp",
  "zoxide",

  "derailed/k9s/k9s",
  "ozeias/postgresql/postgis@15",
]
casks = [
  "android-platform-tools",
  "docker-desktop",
  "font-jetbrains-mono-nerd-font",
  "ghostty",
  "karabiner-elements",
  "kitty",
  "nikitabobko/tap/aerospace",
  "qwerty-fr",
  "spotify",
]
npm = ["@earendil-works/pi-coding-agent"]
